name: ollamachat
version: '1.0.3-hotfix'
main: com.ollamachat.Ollamachat
api-version: '1.21'
authors: [xwwsdd]
description: A plugin used to connect Ollama with Minecraft.
website: https://chat.sarskin.cn/invite/iHgI6LTX

commands:
  ollamachat:
    description: Manage OllamaChat plugin (reload configuration or toggle AI)
    usage: "{usage-ollamachat}"
    permission: ollamachat.admin
  aichat:
    description: Interact with other AI services
    usage: "{usage-aichat}"
    permission: ollamachat.use

permissions:
  ollamachat.admin:
    description: Allows managing the plugin (reload and toggle AI)
    default: op
  ollamachat.use:
    description: Allows using the /aichat command
    default: true