name: OllamaChat
version: '1.1.3'
main: com.ollamachat.core.Ollamachat
api-version: '1.21'
authors: [xwwsdd]
description: A plugin used to connect Ollama and OtherAI with Minecraft.
website: https://chat.sarskin.cn/invite/iHgI6LTX

commands:
  ollamachat:
    description: Manage OllamaChat plugin (reload configuration or toggle AI)
    usage: "{usage-ollamachat}"
    permission: ollamachat.reload
  aichat:
    description: Interact with other AI services
    usage: "{usage-aichat}"
    permission: ollamachat.use

permissions:
  ollamachat.reload:
    description: Allows managing the plugin (reload)
    default: op
  ollamachat.toggle:
    description: Allows managing the plugin (toggle AI)
    default: op
  ollamachat.use:
    description: Allows using the /aichat command
    default: true
  ollamachat.prompt.set:
    description: Allows setting a new prompt
    default: op
  ollamachat.prompt.delete:
    description: Allows deleting a prompt
    default: op
  ollamachat.prompt.list:
    description: Allows listing all prompts
    default: op
  ollamachat.prompt.select:
    description: Allows selecting or clearing a prompt
    default: op
  ollamachat.conversation.new:
    description: Allows creating a new conversation
    default: true
  ollamachat.conversation.select:
    description: Allows selecting a conversation
    default: true
  ollamachat.conversation.list:
    description: Allows listing conversations
    default: true
  ollamachat.conversation.delete:
    description: Allows deleting a conversation
    default: true
  ollamachat.suggests.toggle:
    description: Allows toggling suggested responses on or off
    default: true
  ollamachat.suggests-presets.toggle:
    description: Allows toggling of suggested response presets
    default: op